language: python
python:
- '2.7'
script: echo "HI"
before_install:
- openssl aes-256-cbc -K $encrypted_54303265598a_key -iv $encrypted_54303265598a_iv
  -in config.json.enc -out config.json -d
after_success:
- if [[ $TRAVIS_PULL_REQUEST == 'false' ]]; then
- curl -o $HOME/google_appengine_1.9.25.zip https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.25.zip
- unzip -q -d $HOME $HOME/google_appengine_1.9.25.zip
- "$HOME/google_appengine/appcfg.py -A pipctbot  update --oauth2_refresh_token=$REFRESH_TOKEN
  $TRAVIS_BUILD_DIR"
- fi
env:
  global:
    secure: O0C2f9c7Kw+z9IOXRVFM3nzLo7f64L0cv1EMuqHs55ahJ7MEm7kPIw7eczZZjd79A06e1gni4Y4NHa3G/A+jj4UEKnPNAQ5SDwdBGqu3y9Hoj8u7YqNbIof0cCTiopUItHq05NJ8joe4g0kagc9u+EFOSALxbdhptmQDyVstbzCyLT+sDgkiZsVJh98J6ISugl5SKbqCYBXQDy4mggLNNsn/jATUFwFBIujGwF98fxYEBQANEqxJOPZ8fYGjqeD6aKDKxSnkTp+3ZqEHSdx/rYNETQAYpykjwztIZR2eBMRm54mpelqMP+p0skQIBhT486aAkMfH8ihFRV765OH5nwM3czTsuDV7QJyviukxluIuy2w/lDGJUJ9F7ml2s4O0s0fA2GGjyHE3eN7zbXuc7LyDHbalk7UPVdUt7f6rdfMKkAXnfEN/J2JSM96rg5srW4NoR2/ds1NBYmIBB4chrd/7S46z3/Cl439ADYC9O7KG3scX55RtL2XdxrcPuqAGt/Z6Lll/4BhBwPTg+dyhrEG3w38PoO6RIq0RzfvcExpDmhI30K9zC5clXoIdx2rT1xByTpP1EBMojk5yu5+04g3fj5QwVq4wAGiYl9cANaJEKa4zU6NYcqT+226V/qbFWMjAMoC4GzODtUs9jgMn8prRvB9TU4+FN4k8RWElVw0=
